return {
  'tpope/vim-sleuth',
  { 'tpope/vim-obsession', lazy = false },
  { import = 'custom.plugins.ai' },
  { import = 'custom.plugins.commenting' },
  { import = 'custom.plugins.completion' },
  { import = 'custom.plugins.diagnostics' },
  { import = 'custom.plugins.filetools' },
  { import = 'custom.plugins.git' },
  { import = 'custom.plugins.lsp' },
  { import = 'custom.plugins.productivity' },
  { import = 'custom.plugins.telescope' },
  { import = 'custom.plugins.treesitter' },
  { import = 'custom.plugins.ui' },
}
