/* Automatically generated by tree-sitter v0.25.3 (2a835ee029dca1c325e6f1c01dbce40396f6123e) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 31
#define LARGE_STATE_COUNT 10
#define SYMBOL_COUNT 17
#define ALIAS_COUNT 0
#define TOKEN_COUNT 11
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_IF = 1,
  anon_sym_SEMI = 2,
  anon_sym_END = 3,
  anon_sym_FOR = 4,
  anon_sym_IN = 5,
  anon_sym_BLOCK = 6,
  sym_variable_reference = 7,
  sym_expression = 8,
  sym_identifier = 9,
  sym_other_text = 10,
  sym_source_file = 11,
  sym__statement = 12,
  sym_if_statement = 13,
  sym_for_statement = 14,
  sym_block_statement = 15,
  aux_sym_source_file_repeat1 = 16,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_IF] = "IF",
  [anon_sym_SEMI] = ";",
  [anon_sym_END] = "END",
  [anon_sym_FOR] = "FOR",
  [anon_sym_IN] = "IN",
  [anon_sym_BLOCK] = "BLOCK",
  [sym_variable_reference] = "variable_reference",
  [sym_expression] = "expression",
  [sym_identifier] = "identifier",
  [sym_other_text] = "other_text",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_if_statement] = "if_statement",
  [sym_for_statement] = "for_statement",
  [sym_block_statement] = "block_statement",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_IF] = anon_sym_IF,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_END] = anon_sym_END,
  [anon_sym_FOR] = anon_sym_FOR,
  [anon_sym_IN] = anon_sym_IN,
  [anon_sym_BLOCK] = anon_sym_BLOCK,
  [sym_variable_reference] = sym_variable_reference,
  [sym_expression] = sym_expression,
  [sym_identifier] = sym_identifier,
  [sym_other_text] = sym_other_text,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_if_statement] = sym_if_statement,
  [sym_for_statement] = sym_for_statement,
  [sym_block_statement] = sym_block_statement,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_IF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_END] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_FOR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_IN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BLOCK] = {
    .visible = true,
    .named = false,
  },
  [sym_variable_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_other_text] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_for_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_block_statement] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_block_name = 1,
  field_condition = 2,
  field_item = 3,
  field_list = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_block_name] = "block_name",
  [field_condition] = "condition",
  [field_item] = "item",
  [field_list] = "list",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_condition, 1},
  [1] =
    {field_block_name, 1},
  [2] =
    {field_item, 1},
    {field_list, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      if (lookahead == '$') ADVANCE(13);
      if (lookahead == ';') ADVANCE(17);
      if (lookahead == 'B') ADVANCE(6);
      if (lookahead == 'E') ADVANCE(7);
      if (lookahead == 'F') ADVANCE(8);
      if (lookahead == 'I') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'C') ADVANCE(5);
      END_STATE();
    case 2:
      if (lookahead == 'D') ADVANCE(18);
      END_STATE();
    case 3:
      if (lookahead == 'F') ADVANCE(16);
      END_STATE();
    case 4:
      if (lookahead == 'F') ADVANCE(16);
      if (lookahead == 'N') ADVANCE(20);
      END_STATE();
    case 5:
      if (lookahead == 'K') ADVANCE(21);
      END_STATE();
    case 6:
      if (lookahead == 'L') ADVANCE(9);
      END_STATE();
    case 7:
      if (lookahead == 'N') ADVANCE(2);
      END_STATE();
    case 8:
      if (lookahead == 'O') ADVANCE(10);
      END_STATE();
    case 9:
      if (lookahead == 'O') ADVANCE(1);
      END_STATE();
    case 10:
      if (lookahead == 'R') ADVANCE(19);
      END_STATE();
    case 11:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != ';') ADVANCE(24);
      END_STATE();
    case 12:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 13:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 14:
      if (eof) ADVANCE(15);
      if (lookahead == '$') ADVANCE(13);
      if (lookahead == 'B') ADVANCE(6);
      if (lookahead == 'E') ADVANCE(7);
      if (lookahead == 'F') ADVANCE(8);
      if (lookahead == 'I') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead != 0 &&
          (lookahead < 'B' || 'F' < lookahead) &&
          lookahead != 'K' &&
          lookahead != 'L' &&
          lookahead != 'N' &&
          lookahead != 'O' &&
          lookahead != 'R') ADVANCE(27);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_IF);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_END);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_FOR);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_IN);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_BLOCK);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_variable_reference);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_expression);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != ';') ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_expression);
      if (lookahead != 0 &&
          lookahead != ';') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_other_text);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '$' &&
          (lookahead < 'B' || 'F' < lookahead) &&
          lookahead != 'I' &&
          lookahead != 'K' &&
          lookahead != 'L' &&
          lookahead != 'N' &&
          lookahead != 'O' &&
          lookahead != 'R') ADVANCE(27);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_other_text);
      if (lookahead != 0 &&
          lookahead != '$' &&
          (lookahead < 'B' || 'F' < lookahead) &&
          lookahead != 'I' &&
          lookahead != 'K' &&
          lookahead != 'L' &&
          lookahead != 'N' &&
          lookahead != 'O' &&
          lookahead != 'R') ADVANCE(27);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 14},
  [2] = {.lex_state = 14},
  [3] = {.lex_state = 14},
  [4] = {.lex_state = 14},
  [5] = {.lex_state = 14},
  [6] = {.lex_state = 14},
  [7] = {.lex_state = 14},
  [8] = {.lex_state = 14},
  [9] = {.lex_state = 14},
  [10] = {.lex_state = 14},
  [11] = {.lex_state = 14},
  [12] = {.lex_state = 14},
  [13] = {.lex_state = 14},
  [14] = {.lex_state = 14},
  [15] = {.lex_state = 14},
  [16] = {.lex_state = 11},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 12},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 11},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_IF] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_END] = ACTIONS(1),
    [anon_sym_FOR] = ACTIONS(1),
    [anon_sym_IN] = ACTIONS(1),
    [anon_sym_BLOCK] = ACTIONS(1),
    [sym_variable_reference] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(22),
    [sym__statement] = STATE(3),
    [sym_if_statement] = STATE(3),
    [sym_for_statement] = STATE(3),
    [sym_block_statement] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_IF] = ACTIONS(5),
    [anon_sym_FOR] = ACTIONS(7),
    [anon_sym_BLOCK] = ACTIONS(9),
    [sym_variable_reference] = ACTIONS(11),
    [sym_other_text] = ACTIONS(13),
  },
  [STATE(2)] = {
    [sym__statement] = STATE(2),
    [sym_if_statement] = STATE(2),
    [sym_for_statement] = STATE(2),
    [sym_block_statement] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(15),
    [anon_sym_IF] = ACTIONS(17),
    [anon_sym_END] = ACTIONS(20),
    [anon_sym_FOR] = ACTIONS(22),
    [anon_sym_BLOCK] = ACTIONS(25),
    [sym_variable_reference] = ACTIONS(28),
    [sym_other_text] = ACTIONS(31),
  },
  [STATE(3)] = {
    [sym__statement] = STATE(2),
    [sym_if_statement] = STATE(2),
    [sym_for_statement] = STATE(2),
    [sym_block_statement] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(34),
    [anon_sym_IF] = ACTIONS(5),
    [anon_sym_FOR] = ACTIONS(7),
    [anon_sym_BLOCK] = ACTIONS(9),
    [sym_variable_reference] = ACTIONS(36),
    [sym_other_text] = ACTIONS(38),
  },
  [STATE(4)] = {
    [sym__statement] = STATE(6),
    [sym_if_statement] = STATE(6),
    [sym_for_statement] = STATE(6),
    [sym_block_statement] = STATE(6),
    [aux_sym_source_file_repeat1] = STATE(6),
    [anon_sym_IF] = ACTIONS(5),
    [anon_sym_END] = ACTIONS(40),
    [anon_sym_FOR] = ACTIONS(7),
    [anon_sym_BLOCK] = ACTIONS(9),
    [sym_variable_reference] = ACTIONS(42),
    [sym_other_text] = ACTIONS(44),
  },
  [STATE(5)] = {
    [sym__statement] = STATE(8),
    [sym_if_statement] = STATE(8),
    [sym_for_statement] = STATE(8),
    [sym_block_statement] = STATE(8),
    [aux_sym_source_file_repeat1] = STATE(8),
    [anon_sym_IF] = ACTIONS(5),
    [anon_sym_END] = ACTIONS(46),
    [anon_sym_FOR] = ACTIONS(7),
    [anon_sym_BLOCK] = ACTIONS(9),
    [sym_variable_reference] = ACTIONS(48),
    [sym_other_text] = ACTIONS(50),
  },
  [STATE(6)] = {
    [sym__statement] = STATE(2),
    [sym_if_statement] = STATE(2),
    [sym_for_statement] = STATE(2),
    [sym_block_statement] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [anon_sym_IF] = ACTIONS(5),
    [anon_sym_END] = ACTIONS(52),
    [anon_sym_FOR] = ACTIONS(7),
    [anon_sym_BLOCK] = ACTIONS(9),
    [sym_variable_reference] = ACTIONS(36),
    [sym_other_text] = ACTIONS(38),
  },
  [STATE(7)] = {
    [sym__statement] = STATE(9),
    [sym_if_statement] = STATE(9),
    [sym_for_statement] = STATE(9),
    [sym_block_statement] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(9),
    [anon_sym_IF] = ACTIONS(5),
    [anon_sym_END] = ACTIONS(54),
    [anon_sym_FOR] = ACTIONS(7),
    [anon_sym_BLOCK] = ACTIONS(9),
    [sym_variable_reference] = ACTIONS(56),
    [sym_other_text] = ACTIONS(58),
  },
  [STATE(8)] = {
    [sym__statement] = STATE(2),
    [sym_if_statement] = STATE(2),
    [sym_for_statement] = STATE(2),
    [sym_block_statement] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [anon_sym_IF] = ACTIONS(5),
    [anon_sym_END] = ACTIONS(60),
    [anon_sym_FOR] = ACTIONS(7),
    [anon_sym_BLOCK] = ACTIONS(9),
    [sym_variable_reference] = ACTIONS(36),
    [sym_other_text] = ACTIONS(38),
  },
  [STATE(9)] = {
    [sym__statement] = STATE(2),
    [sym_if_statement] = STATE(2),
    [sym_for_statement] = STATE(2),
    [sym_block_statement] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [anon_sym_IF] = ACTIONS(5),
    [anon_sym_END] = ACTIONS(62),
    [anon_sym_FOR] = ACTIONS(7),
    [anon_sym_BLOCK] = ACTIONS(9),
    [sym_variable_reference] = ACTIONS(36),
    [sym_other_text] = ACTIONS(38),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(64), 2,
      ts_builtin_sym_end,
      sym_other_text,
    ACTIONS(66), 5,
      anon_sym_IF,
      anon_sym_END,
      anon_sym_FOR,
      anon_sym_BLOCK,
      sym_variable_reference,
  [12] = 2,
    ACTIONS(68), 2,
      ts_builtin_sym_end,
      sym_other_text,
    ACTIONS(70), 5,
      anon_sym_IF,
      anon_sym_END,
      anon_sym_FOR,
      anon_sym_BLOCK,
      sym_variable_reference,
  [24] = 2,
    ACTIONS(72), 2,
      ts_builtin_sym_end,
      sym_other_text,
    ACTIONS(74), 5,
      anon_sym_IF,
      anon_sym_END,
      anon_sym_FOR,
      anon_sym_BLOCK,
      sym_variable_reference,
  [36] = 2,
    ACTIONS(76), 2,
      ts_builtin_sym_end,
      sym_other_text,
    ACTIONS(78), 5,
      anon_sym_IF,
      anon_sym_END,
      anon_sym_FOR,
      anon_sym_BLOCK,
      sym_variable_reference,
  [48] = 2,
    ACTIONS(80), 2,
      ts_builtin_sym_end,
      sym_other_text,
    ACTIONS(82), 5,
      anon_sym_IF,
      anon_sym_END,
      anon_sym_FOR,
      anon_sym_BLOCK,
      sym_variable_reference,
  [60] = 2,
    ACTIONS(84), 2,
      ts_builtin_sym_end,
      sym_other_text,
    ACTIONS(86), 5,
      anon_sym_IF,
      anon_sym_END,
      anon_sym_FOR,
      anon_sym_BLOCK,
      sym_variable_reference,
  [72] = 1,
    ACTIONS(88), 1,
      sym_expression,
  [76] = 1,
    ACTIONS(90), 1,
      sym_variable_reference,
  [80] = 1,
    ACTIONS(92), 1,
      sym_identifier,
  [84] = 1,
    ACTIONS(94), 1,
      anon_sym_SEMI,
  [88] = 1,
    ACTIONS(96), 1,
      anon_sym_SEMI,
  [92] = 1,
    ACTIONS(98), 1,
      anon_sym_IN,
  [96] = 1,
    ACTIONS(100), 1,
      ts_builtin_sym_end,
  [100] = 1,
    ACTIONS(102), 1,
      sym_expression,
  [104] = 1,
    ACTIONS(104), 1,
      anon_sym_SEMI,
  [108] = 1,
    ACTIONS(106), 1,
      anon_sym_SEMI,
  [112] = 1,
    ACTIONS(108), 1,
      anon_sym_SEMI,
  [116] = 1,
    ACTIONS(110), 1,
      anon_sym_SEMI,
  [120] = 1,
    ACTIONS(112), 1,
      anon_sym_SEMI,
  [124] = 1,
    ACTIONS(114), 1,
      anon_sym_SEMI,
  [128] = 1,
    ACTIONS(116), 1,
      anon_sym_SEMI,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(10)] = 0,
  [SMALL_STATE(11)] = 12,
  [SMALL_STATE(12)] = 24,
  [SMALL_STATE(13)] = 36,
  [SMALL_STATE(14)] = 48,
  [SMALL_STATE(15)] = 60,
  [SMALL_STATE(16)] = 72,
  [SMALL_STATE(17)] = 76,
  [SMALL_STATE(18)] = 80,
  [SMALL_STATE(19)] = 84,
  [SMALL_STATE(20)] = 88,
  [SMALL_STATE(21)] = 92,
  [SMALL_STATE(22)] = 96,
  [SMALL_STATE(23)] = 100,
  [SMALL_STATE(24)] = 104,
  [SMALL_STATE(25)] = 108,
  [SMALL_STATE(26)] = 112,
  [SMALL_STATE(27)] = 116,
  [SMALL_STATE(28)] = 120,
  [SMALL_STATE(29)] = 124,
  [SMALL_STATE(30)] = 128,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [20] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [22] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [40] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [42] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [46] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 6, 0, 1),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 6, 0, 1),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 5, 0, 1),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 5, 0, 1),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_statement, 6, 0, 2),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_statement, 6, 0, 2),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_statement, 5, 0, 2),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_statement, 5, 0, 2),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_for_statement, 7, 0, 3),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_for_statement, 7, 0, 3),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_for_statement, 8, 0, 3),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_for_statement, 8, 0, 3),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [100] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_tt2(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "tt2",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
