/* Automatically generated by tree-sitter v0.25.3 (2a835ee029dca1c325e6f1c01dbce40396f6123e) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 66
#define LARGE_STATE_COUNT 17
#define SYMBOL_COUNT 20
#define ALIAS_COUNT 0
#define TOKEN_COUNT 13
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_IF = 1,
  anon_sym_SEMI = 2,
  anon_sym_END = 3,
  anon_sym_FOR = 4,
  anon_sym_IN = 5,
  anon_sym_BLOCK = 6,
  sym_variable_reference = 7,
  sym_expression = 8,
  sym_identifier = 9,
  anon_sym_LBRACK_PERCENT_DASH = 10,
  anon_sym_DASH_PERCENT_RBRACK = 11,
  sym_other_text = 12,
  sym_source_file = 13,
  sym__statement = 14,
  sym_if_statement = 15,
  sym_for_statement = 16,
  sym_block_statement = 17,
  sym_template_tag = 18,
  aux_sym_source_file_repeat1 = 19,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_IF] = "IF",
  [anon_sym_SEMI] = ";",
  [anon_sym_END] = "END",
  [anon_sym_FOR] = "FOR",
  [anon_sym_IN] = "IN",
  [anon_sym_BLOCK] = "BLOCK",
  [sym_variable_reference] = "variable_reference",
  [sym_expression] = "expression",
  [sym_identifier] = "identifier",
  [anon_sym_LBRACK_PERCENT_DASH] = "[%-",
  [anon_sym_DASH_PERCENT_RBRACK] = "-%]",
  [sym_other_text] = "other_text",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_if_statement] = "if_statement",
  [sym_for_statement] = "for_statement",
  [sym_block_statement] = "block_statement",
  [sym_template_tag] = "template_tag",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_IF] = anon_sym_IF,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_END] = anon_sym_END,
  [anon_sym_FOR] = anon_sym_FOR,
  [anon_sym_IN] = anon_sym_IN,
  [anon_sym_BLOCK] = anon_sym_BLOCK,
  [sym_variable_reference] = sym_variable_reference,
  [sym_expression] = sym_expression,
  [sym_identifier] = sym_identifier,
  [anon_sym_LBRACK_PERCENT_DASH] = anon_sym_LBRACK_PERCENT_DASH,
  [anon_sym_DASH_PERCENT_RBRACK] = anon_sym_DASH_PERCENT_RBRACK,
  [sym_other_text] = sym_other_text,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_if_statement] = sym_if_statement,
  [sym_for_statement] = sym_for_statement,
  [sym_block_statement] = sym_block_statement,
  [sym_template_tag] = sym_template_tag,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_IF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_END] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_FOR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_IN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BLOCK] = {
    .visible = true,
    .named = false,
  },
  [sym_variable_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK_PERCENT_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_PERCENT_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_other_text] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_for_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_block_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_template_tag] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_block_name = 1,
  field_condition = 2,
  field_item = 3,
  field_list = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_block_name] = "block_name",
  [field_condition] = "condition",
  [field_item] = "item",
  [field_list] = "list",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_condition, 1},
  [1] =
    {field_block_name, 1},
  [2] =
    {field_item, 1},
    {field_list, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 2,
  [10] = 10,
  [11] = 3,
  [12] = 4,
  [13] = 5,
  [14] = 6,
  [15] = 7,
  [16] = 8,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 17,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 18,
  [27] = 19,
  [28] = 21,
  [29] = 22,
  [30] = 23,
  [31] = 24,
  [32] = 25,
  [33] = 33,
  [34] = 33,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 35,
  [43] = 43,
  [44] = 44,
  [45] = 39,
  [46] = 46,
  [47] = 47,
  [48] = 43,
  [49] = 37,
  [50] = 40,
  [51] = 44,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 47,
  [57] = 57,
  [58] = 52,
  [59] = 57,
  [60] = 46,
  [61] = 38,
  [62] = 54,
  [63] = 55,
  [64] = 41,
  [65] = 53,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(20);
      ADVANCE_MAP(
        '$', 18,
        '-', 2,
        ';', 23,
        'B', 10,
        'E', 11,
        'F', 12,
        'I', 8,
        '[', 3,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '$') ADVANCE(53);
      if (lookahead == 'B') ADVANCE(48);
      if (lookahead == 'E') ADVANCE(49);
      if (lookahead == 'F') ADVANCE(50);
      if (lookahead == 'I') ADVANCE(46);
      if (lookahead == '[') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(54);
      END_STATE();
    case 2:
      if (lookahead == '%') ADVANCE(15);
      END_STATE();
    case 3:
      if (lookahead == '%') ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(39);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(33);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != ';') ADVANCE(37);
      END_STATE();
    case 6:
      if (lookahead == 'C') ADVANCE(9);
      END_STATE();
    case 7:
      if (lookahead == 'D') ADVANCE(24);
      END_STATE();
    case 8:
      if (lookahead == 'F') ADVANCE(21);
      if (lookahead == 'N') ADVANCE(28);
      END_STATE();
    case 9:
      if (lookahead == 'K') ADVANCE(29);
      END_STATE();
    case 10:
      if (lookahead == 'L') ADVANCE(13);
      END_STATE();
    case 11:
      if (lookahead == 'N') ADVANCE(7);
      END_STATE();
    case 12:
      if (lookahead == 'O') ADVANCE(14);
      END_STATE();
    case 13:
      if (lookahead == 'O') ADVANCE(6);
      END_STATE();
    case 14:
      if (lookahead == 'R') ADVANCE(26);
      END_STATE();
    case 15:
      if (lookahead == ']') ADVANCE(40);
      END_STATE();
    case 16:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != ';') ADVANCE(37);
      END_STATE();
    case 17:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(17);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 18:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 19:
      if (eof) ADVANCE(20);
      if (lookahead == '$') ADVANCE(53);
      if (lookahead == 'B') ADVANCE(48);
      if (lookahead == 'F') ADVANCE(50);
      if (lookahead == 'I') ADVANCE(46);
      if (lookahead == '[') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(54);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_IF);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_IF);
      if (lookahead != 0 &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(54);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_END);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_END);
      if (lookahead != 0 &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(54);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_FOR);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_FOR);
      if (lookahead != 0 &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(54);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_IN);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_BLOCK);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_BLOCK);
      if (lookahead != 0 &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(54);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_variable_reference);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_variable_reference);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      if (lookahead != 0 &&
          (lookahead < 'A' || '[' < lookahead) &&
          lookahead != ']') ADVANCE(54);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_expression);
      if (lookahead == '%') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != ';') ADVANCE(37);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_expression);
      if (lookahead == '-') ADVANCE(33);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != ';') ADVANCE(37);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_expression);
      if (lookahead == ']') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != ';') ADVANCE(37);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_expression);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != ';') ADVANCE(37);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_expression);
      if (lookahead != 0 &&
          lookahead != ';') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LBRACK_PERCENT_DASH);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_DASH_PERCENT_RBRACK);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_DASH_PERCENT_RBRACK);
      if (lookahead != 0 &&
          lookahead != ';') ADVANCE(37);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_other_text);
      if (lookahead == '$') ADVANCE(53);
      if (lookahead == 'B') ADVANCE(48);
      if (lookahead == 'E') ADVANCE(49);
      if (lookahead == 'F') ADVANCE(50);
      if (lookahead == 'I') ADVANCE(46);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(54);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_other_text);
      if (lookahead == '$') ADVANCE(53);
      if (lookahead == 'B') ADVANCE(48);
      if (lookahead == 'F') ADVANCE(50);
      if (lookahead == 'I') ADVANCE(46);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(54);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_other_text);
      if (lookahead == 'C') ADVANCE(47);
      if (lookahead != 0 &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(54);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_other_text);
      if (lookahead == 'D') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(54);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_other_text);
      if (lookahead == 'F') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(54);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_other_text);
      if (lookahead == 'K') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(54);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_other_text);
      if (lookahead == 'L') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(54);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_other_text);
      if (lookahead == 'N') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(54);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_other_text);
      if (lookahead == 'O') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(54);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_other_text);
      if (lookahead == 'O') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(54);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_other_text);
      if (lookahead == 'R') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(54);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_other_text);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      if (lookahead != 0 &&
          (lookahead < 'A' || '[' < lookahead) &&
          lookahead != ']') ADVANCE(54);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_other_text);
      if (lookahead != 0 &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(54);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 19},
  [2] = {.lex_state = 19},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 19},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 19},
  [19] = {.lex_state = 19},
  [20] = {.lex_state = 19},
  [21] = {.lex_state = 19},
  [22] = {.lex_state = 19},
  [23] = {.lex_state = 19},
  [24] = {.lex_state = 19},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 19},
  [33] = {.lex_state = 5},
  [34] = {.lex_state = 5},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 16},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 17},
  [55] = {.lex_state = 16},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 16},
  [62] = {.lex_state = 17},
  [63] = {.lex_state = 16},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_IF] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_END] = ACTIONS(1),
    [anon_sym_FOR] = ACTIONS(1),
    [anon_sym_IN] = ACTIONS(1),
    [anon_sym_BLOCK] = ACTIONS(1),
    [sym_variable_reference] = ACTIONS(1),
    [anon_sym_LBRACK_PERCENT_DASH] = ACTIONS(1),
    [anon_sym_DASH_PERCENT_RBRACK] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(36),
    [sym__statement] = STATE(10),
    [sym_if_statement] = STATE(10),
    [sym_for_statement] = STATE(10),
    [sym_block_statement] = STATE(10),
    [sym_template_tag] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_IF] = ACTIONS(5),
    [anon_sym_FOR] = ACTIONS(7),
    [anon_sym_BLOCK] = ACTIONS(9),
    [sym_variable_reference] = ACTIONS(11),
    [anon_sym_LBRACK_PERCENT_DASH] = ACTIONS(13),
    [sym_other_text] = ACTIONS(11),
  },
  [STATE(2)] = {
    [sym__statement] = STATE(2),
    [sym_if_statement] = STATE(2),
    [sym_for_statement] = STATE(2),
    [sym_block_statement] = STATE(2),
    [sym_template_tag] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(15),
    [anon_sym_IF] = ACTIONS(17),
    [anon_sym_FOR] = ACTIONS(20),
    [anon_sym_BLOCK] = ACTIONS(23),
    [sym_variable_reference] = ACTIONS(26),
    [anon_sym_LBRACK_PERCENT_DASH] = ACTIONS(29),
    [sym_other_text] = ACTIONS(26),
  },
  [STATE(3)] = {
    [sym__statement] = STATE(5),
    [sym_if_statement] = STATE(5),
    [sym_for_statement] = STATE(5),
    [sym_block_statement] = STATE(5),
    [sym_template_tag] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [anon_sym_IF] = ACTIONS(32),
    [anon_sym_END] = ACTIONS(34),
    [anon_sym_FOR] = ACTIONS(36),
    [anon_sym_BLOCK] = ACTIONS(38),
    [sym_variable_reference] = ACTIONS(40),
    [anon_sym_LBRACK_PERCENT_DASH] = ACTIONS(42),
    [sym_other_text] = ACTIONS(40),
  },
  [STATE(4)] = {
    [sym__statement] = STATE(6),
    [sym_if_statement] = STATE(6),
    [sym_for_statement] = STATE(6),
    [sym_block_statement] = STATE(6),
    [sym_template_tag] = STATE(6),
    [aux_sym_source_file_repeat1] = STATE(6),
    [anon_sym_IF] = ACTIONS(32),
    [anon_sym_END] = ACTIONS(44),
    [anon_sym_FOR] = ACTIONS(36),
    [anon_sym_BLOCK] = ACTIONS(38),
    [sym_variable_reference] = ACTIONS(46),
    [anon_sym_LBRACK_PERCENT_DASH] = ACTIONS(42),
    [sym_other_text] = ACTIONS(46),
  },
  [STATE(5)] = {
    [sym__statement] = STATE(9),
    [sym_if_statement] = STATE(9),
    [sym_for_statement] = STATE(9),
    [sym_block_statement] = STATE(9),
    [sym_template_tag] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(9),
    [anon_sym_IF] = ACTIONS(32),
    [anon_sym_END] = ACTIONS(48),
    [anon_sym_FOR] = ACTIONS(36),
    [anon_sym_BLOCK] = ACTIONS(38),
    [sym_variable_reference] = ACTIONS(50),
    [anon_sym_LBRACK_PERCENT_DASH] = ACTIONS(42),
    [sym_other_text] = ACTIONS(50),
  },
  [STATE(6)] = {
    [sym__statement] = STATE(9),
    [sym_if_statement] = STATE(9),
    [sym_for_statement] = STATE(9),
    [sym_block_statement] = STATE(9),
    [sym_template_tag] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(9),
    [anon_sym_IF] = ACTIONS(32),
    [anon_sym_END] = ACTIONS(52),
    [anon_sym_FOR] = ACTIONS(36),
    [anon_sym_BLOCK] = ACTIONS(38),
    [sym_variable_reference] = ACTIONS(50),
    [anon_sym_LBRACK_PERCENT_DASH] = ACTIONS(42),
    [sym_other_text] = ACTIONS(50),
  },
  [STATE(7)] = {
    [sym__statement] = STATE(8),
    [sym_if_statement] = STATE(8),
    [sym_for_statement] = STATE(8),
    [sym_block_statement] = STATE(8),
    [sym_template_tag] = STATE(8),
    [aux_sym_source_file_repeat1] = STATE(8),
    [anon_sym_IF] = ACTIONS(32),
    [anon_sym_END] = ACTIONS(54),
    [anon_sym_FOR] = ACTIONS(36),
    [anon_sym_BLOCK] = ACTIONS(38),
    [sym_variable_reference] = ACTIONS(56),
    [anon_sym_LBRACK_PERCENT_DASH] = ACTIONS(42),
    [sym_other_text] = ACTIONS(56),
  },
  [STATE(8)] = {
    [sym__statement] = STATE(9),
    [sym_if_statement] = STATE(9),
    [sym_for_statement] = STATE(9),
    [sym_block_statement] = STATE(9),
    [sym_template_tag] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(9),
    [anon_sym_IF] = ACTIONS(32),
    [anon_sym_END] = ACTIONS(58),
    [anon_sym_FOR] = ACTIONS(36),
    [anon_sym_BLOCK] = ACTIONS(38),
    [sym_variable_reference] = ACTIONS(50),
    [anon_sym_LBRACK_PERCENT_DASH] = ACTIONS(42),
    [sym_other_text] = ACTIONS(50),
  },
  [STATE(9)] = {
    [sym__statement] = STATE(9),
    [sym_if_statement] = STATE(9),
    [sym_for_statement] = STATE(9),
    [sym_block_statement] = STATE(9),
    [sym_template_tag] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(9),
    [anon_sym_IF] = ACTIONS(60),
    [anon_sym_END] = ACTIONS(63),
    [anon_sym_FOR] = ACTIONS(65),
    [anon_sym_BLOCK] = ACTIONS(68),
    [sym_variable_reference] = ACTIONS(71),
    [anon_sym_LBRACK_PERCENT_DASH] = ACTIONS(74),
    [sym_other_text] = ACTIONS(71),
  },
  [STATE(10)] = {
    [sym__statement] = STATE(2),
    [sym_if_statement] = STATE(2),
    [sym_for_statement] = STATE(2),
    [sym_block_statement] = STATE(2),
    [sym_template_tag] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(77),
    [anon_sym_IF] = ACTIONS(5),
    [anon_sym_FOR] = ACTIONS(7),
    [anon_sym_BLOCK] = ACTIONS(9),
    [sym_variable_reference] = ACTIONS(79),
    [anon_sym_LBRACK_PERCENT_DASH] = ACTIONS(13),
    [sym_other_text] = ACTIONS(79),
  },
  [STATE(11)] = {
    [sym__statement] = STATE(13),
    [sym_if_statement] = STATE(13),
    [sym_for_statement] = STATE(13),
    [sym_block_statement] = STATE(13),
    [sym_template_tag] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(13),
    [anon_sym_IF] = ACTIONS(32),
    [anon_sym_END] = ACTIONS(81),
    [anon_sym_FOR] = ACTIONS(36),
    [anon_sym_BLOCK] = ACTIONS(38),
    [sym_variable_reference] = ACTIONS(83),
    [anon_sym_LBRACK_PERCENT_DASH] = ACTIONS(42),
    [sym_other_text] = ACTIONS(83),
  },
  [STATE(12)] = {
    [sym__statement] = STATE(14),
    [sym_if_statement] = STATE(14),
    [sym_for_statement] = STATE(14),
    [sym_block_statement] = STATE(14),
    [sym_template_tag] = STATE(14),
    [aux_sym_source_file_repeat1] = STATE(14),
    [anon_sym_IF] = ACTIONS(32),
    [anon_sym_END] = ACTIONS(85),
    [anon_sym_FOR] = ACTIONS(36),
    [anon_sym_BLOCK] = ACTIONS(38),
    [sym_variable_reference] = ACTIONS(87),
    [anon_sym_LBRACK_PERCENT_DASH] = ACTIONS(42),
    [sym_other_text] = ACTIONS(87),
  },
  [STATE(13)] = {
    [sym__statement] = STATE(9),
    [sym_if_statement] = STATE(9),
    [sym_for_statement] = STATE(9),
    [sym_block_statement] = STATE(9),
    [sym_template_tag] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(9),
    [anon_sym_IF] = ACTIONS(32),
    [anon_sym_END] = ACTIONS(89),
    [anon_sym_FOR] = ACTIONS(36),
    [anon_sym_BLOCK] = ACTIONS(38),
    [sym_variable_reference] = ACTIONS(50),
    [anon_sym_LBRACK_PERCENT_DASH] = ACTIONS(42),
    [sym_other_text] = ACTIONS(50),
  },
  [STATE(14)] = {
    [sym__statement] = STATE(9),
    [sym_if_statement] = STATE(9),
    [sym_for_statement] = STATE(9),
    [sym_block_statement] = STATE(9),
    [sym_template_tag] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(9),
    [anon_sym_IF] = ACTIONS(32),
    [anon_sym_END] = ACTIONS(91),
    [anon_sym_FOR] = ACTIONS(36),
    [anon_sym_BLOCK] = ACTIONS(38),
    [sym_variable_reference] = ACTIONS(50),
    [anon_sym_LBRACK_PERCENT_DASH] = ACTIONS(42),
    [sym_other_text] = ACTIONS(50),
  },
  [STATE(15)] = {
    [sym__statement] = STATE(16),
    [sym_if_statement] = STATE(16),
    [sym_for_statement] = STATE(16),
    [sym_block_statement] = STATE(16),
    [sym_template_tag] = STATE(16),
    [aux_sym_source_file_repeat1] = STATE(16),
    [anon_sym_IF] = ACTIONS(32),
    [anon_sym_END] = ACTIONS(93),
    [anon_sym_FOR] = ACTIONS(36),
    [anon_sym_BLOCK] = ACTIONS(38),
    [sym_variable_reference] = ACTIONS(95),
    [anon_sym_LBRACK_PERCENT_DASH] = ACTIONS(42),
    [sym_other_text] = ACTIONS(95),
  },
  [STATE(16)] = {
    [sym__statement] = STATE(9),
    [sym_if_statement] = STATE(9),
    [sym_for_statement] = STATE(9),
    [sym_block_statement] = STATE(9),
    [sym_template_tag] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(9),
    [anon_sym_IF] = ACTIONS(32),
    [anon_sym_END] = ACTIONS(97),
    [anon_sym_FOR] = ACTIONS(36),
    [anon_sym_BLOCK] = ACTIONS(38),
    [sym_variable_reference] = ACTIONS(50),
    [anon_sym_LBRACK_PERCENT_DASH] = ACTIONS(42),
    [sym_other_text] = ACTIONS(50),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(99), 7,
      anon_sym_IF,
      anon_sym_END,
      anon_sym_FOR,
      anon_sym_BLOCK,
      sym_variable_reference,
      anon_sym_LBRACK_PERCENT_DASH,
      sym_other_text,
  [10] = 2,
    ACTIONS(101), 1,
      ts_builtin_sym_end,
    ACTIONS(103), 6,
      anon_sym_IF,
      anon_sym_FOR,
      anon_sym_BLOCK,
      sym_variable_reference,
      anon_sym_LBRACK_PERCENT_DASH,
      sym_other_text,
  [22] = 2,
    ACTIONS(105), 1,
      ts_builtin_sym_end,
    ACTIONS(107), 6,
      anon_sym_IF,
      anon_sym_FOR,
      anon_sym_BLOCK,
      sym_variable_reference,
      anon_sym_LBRACK_PERCENT_DASH,
      sym_other_text,
  [34] = 2,
    ACTIONS(109), 1,
      ts_builtin_sym_end,
    ACTIONS(99), 6,
      anon_sym_IF,
      anon_sym_FOR,
      anon_sym_BLOCK,
      sym_variable_reference,
      anon_sym_LBRACK_PERCENT_DASH,
      sym_other_text,
  [46] = 2,
    ACTIONS(111), 1,
      ts_builtin_sym_end,
    ACTIONS(113), 6,
      anon_sym_IF,
      anon_sym_FOR,
      anon_sym_BLOCK,
      sym_variable_reference,
      anon_sym_LBRACK_PERCENT_DASH,
      sym_other_text,
  [58] = 2,
    ACTIONS(115), 1,
      ts_builtin_sym_end,
    ACTIONS(117), 6,
      anon_sym_IF,
      anon_sym_FOR,
      anon_sym_BLOCK,
      sym_variable_reference,
      anon_sym_LBRACK_PERCENT_DASH,
      sym_other_text,
  [70] = 2,
    ACTIONS(119), 1,
      ts_builtin_sym_end,
    ACTIONS(121), 6,
      anon_sym_IF,
      anon_sym_FOR,
      anon_sym_BLOCK,
      sym_variable_reference,
      anon_sym_LBRACK_PERCENT_DASH,
      sym_other_text,
  [82] = 2,
    ACTIONS(123), 1,
      ts_builtin_sym_end,
    ACTIONS(125), 6,
      anon_sym_IF,
      anon_sym_FOR,
      anon_sym_BLOCK,
      sym_variable_reference,
      anon_sym_LBRACK_PERCENT_DASH,
      sym_other_text,
  [94] = 1,
    ACTIONS(127), 7,
      anon_sym_IF,
      anon_sym_END,
      anon_sym_FOR,
      anon_sym_BLOCK,
      sym_variable_reference,
      anon_sym_LBRACK_PERCENT_DASH,
      sym_other_text,
  [104] = 1,
    ACTIONS(103), 7,
      anon_sym_IF,
      anon_sym_END,
      anon_sym_FOR,
      anon_sym_BLOCK,
      sym_variable_reference,
      anon_sym_LBRACK_PERCENT_DASH,
      sym_other_text,
  [114] = 1,
    ACTIONS(107), 7,
      anon_sym_IF,
      anon_sym_END,
      anon_sym_FOR,
      anon_sym_BLOCK,
      sym_variable_reference,
      anon_sym_LBRACK_PERCENT_DASH,
      sym_other_text,
  [124] = 1,
    ACTIONS(113), 7,
      anon_sym_IF,
      anon_sym_END,
      anon_sym_FOR,
      anon_sym_BLOCK,
      sym_variable_reference,
      anon_sym_LBRACK_PERCENT_DASH,
      sym_other_text,
  [134] = 1,
    ACTIONS(117), 7,
      anon_sym_IF,
      anon_sym_END,
      anon_sym_FOR,
      anon_sym_BLOCK,
      sym_variable_reference,
      anon_sym_LBRACK_PERCENT_DASH,
      sym_other_text,
  [144] = 1,
    ACTIONS(121), 7,
      anon_sym_IF,
      anon_sym_END,
      anon_sym_FOR,
      anon_sym_BLOCK,
      sym_variable_reference,
      anon_sym_LBRACK_PERCENT_DASH,
      sym_other_text,
  [154] = 1,
    ACTIONS(125), 7,
      anon_sym_IF,
      anon_sym_END,
      anon_sym_FOR,
      anon_sym_BLOCK,
      sym_variable_reference,
      anon_sym_LBRACK_PERCENT_DASH,
      sym_other_text,
  [164] = 2,
    ACTIONS(129), 1,
      ts_builtin_sym_end,
    ACTIONS(127), 6,
      anon_sym_IF,
      anon_sym_FOR,
      anon_sym_BLOCK,
      sym_variable_reference,
      anon_sym_LBRACK_PERCENT_DASH,
      sym_other_text,
  [176] = 2,
    ACTIONS(131), 1,
      sym_expression,
    ACTIONS(133), 1,
      anon_sym_DASH_PERCENT_RBRACK,
  [183] = 2,
    ACTIONS(135), 1,
      sym_expression,
    ACTIONS(137), 1,
      anon_sym_DASH_PERCENT_RBRACK,
  [190] = 1,
    ACTIONS(139), 1,
      anon_sym_SEMI,
  [194] = 1,
    ACTIONS(141), 1,
      ts_builtin_sym_end,
  [198] = 1,
    ACTIONS(143), 1,
      anon_sym_SEMI,
  [202] = 1,
    ACTIONS(145), 1,
      sym_expression,
  [206] = 1,
    ACTIONS(147), 1,
      anon_sym_DASH_PERCENT_RBRACK,
  [210] = 1,
    ACTIONS(149), 1,
      anon_sym_SEMI,
  [214] = 1,
    ACTIONS(151), 1,
      anon_sym_IN,
  [218] = 1,
    ACTIONS(153), 1,
      anon_sym_SEMI,
  [222] = 1,
    ACTIONS(155), 1,
      anon_sym_SEMI,
  [226] = 1,
    ACTIONS(157), 1,
      anon_sym_SEMI,
  [230] = 1,
    ACTIONS(159), 1,
      anon_sym_DASH_PERCENT_RBRACK,
  [234] = 1,
    ACTIONS(161), 1,
      anon_sym_SEMI,
  [238] = 1,
    ACTIONS(163), 1,
      anon_sym_SEMI,
  [242] = 1,
    ACTIONS(165), 1,
      anon_sym_SEMI,
  [246] = 1,
    ACTIONS(167), 1,
      anon_sym_SEMI,
  [250] = 1,
    ACTIONS(169), 1,
      anon_sym_SEMI,
  [254] = 1,
    ACTIONS(171), 1,
      anon_sym_SEMI,
  [258] = 1,
    ACTIONS(173), 1,
      anon_sym_SEMI,
  [262] = 1,
    ACTIONS(175), 1,
      sym_variable_reference,
  [266] = 1,
    ACTIONS(177), 1,
      sym_identifier,
  [270] = 1,
    ACTIONS(179), 1,
      sym_expression,
  [274] = 1,
    ACTIONS(181), 1,
      anon_sym_SEMI,
  [278] = 1,
    ACTIONS(183), 1,
      anon_sym_SEMI,
  [282] = 1,
    ACTIONS(185), 1,
      anon_sym_SEMI,
  [286] = 1,
    ACTIONS(187), 1,
      anon_sym_SEMI,
  [290] = 1,
    ACTIONS(189), 1,
      anon_sym_SEMI,
  [294] = 1,
    ACTIONS(191), 1,
      sym_expression,
  [298] = 1,
    ACTIONS(193), 1,
      sym_identifier,
  [302] = 1,
    ACTIONS(195), 1,
      sym_expression,
  [306] = 1,
    ACTIONS(197), 1,
      anon_sym_IN,
  [310] = 1,
    ACTIONS(199), 1,
      sym_variable_reference,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(17)] = 0,
  [SMALL_STATE(18)] = 10,
  [SMALL_STATE(19)] = 22,
  [SMALL_STATE(20)] = 34,
  [SMALL_STATE(21)] = 46,
  [SMALL_STATE(22)] = 58,
  [SMALL_STATE(23)] = 70,
  [SMALL_STATE(24)] = 82,
  [SMALL_STATE(25)] = 94,
  [SMALL_STATE(26)] = 104,
  [SMALL_STATE(27)] = 114,
  [SMALL_STATE(28)] = 124,
  [SMALL_STATE(29)] = 134,
  [SMALL_STATE(30)] = 144,
  [SMALL_STATE(31)] = 154,
  [SMALL_STATE(32)] = 164,
  [SMALL_STATE(33)] = 176,
  [SMALL_STATE(34)] = 183,
  [SMALL_STATE(35)] = 190,
  [SMALL_STATE(36)] = 194,
  [SMALL_STATE(37)] = 198,
  [SMALL_STATE(38)] = 202,
  [SMALL_STATE(39)] = 206,
  [SMALL_STATE(40)] = 210,
  [SMALL_STATE(41)] = 214,
  [SMALL_STATE(42)] = 218,
  [SMALL_STATE(43)] = 222,
  [SMALL_STATE(44)] = 226,
  [SMALL_STATE(45)] = 230,
  [SMALL_STATE(46)] = 234,
  [SMALL_STATE(47)] = 238,
  [SMALL_STATE(48)] = 242,
  [SMALL_STATE(49)] = 246,
  [SMALL_STATE(50)] = 250,
  [SMALL_STATE(51)] = 254,
  [SMALL_STATE(52)] = 258,
  [SMALL_STATE(53)] = 262,
  [SMALL_STATE(54)] = 266,
  [SMALL_STATE(55)] = 270,
  [SMALL_STATE(56)] = 274,
  [SMALL_STATE(57)] = 278,
  [SMALL_STATE(58)] = 282,
  [SMALL_STATE(59)] = 286,
  [SMALL_STATE(60)] = 290,
  [SMALL_STATE(61)] = 294,
  [SMALL_STATE(62)] = 298,
  [SMALL_STATE(63)] = 302,
  [SMALL_STATE(64)] = 306,
  [SMALL_STATE(65)] = 310,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [20] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [32] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [34] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [36] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [38] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [40] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [42] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [46] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [68] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [71] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [74] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_statement, 5, 0, 2),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template_tag, 3, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_template_tag, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 5, 0, 1),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 5, 0, 1),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_statement, 5, 0, 2),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 6, 0, 1),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 6, 0, 1),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_statement, 6, 0, 2),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_statement, 6, 0, 2),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_for_statement, 7, 0, 3),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_for_statement, 7, 0, 3),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_for_statement, 8, 0, 3),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_for_statement, 8, 0, 3),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_template_tag, 2, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template_tag, 2, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [137] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [141] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_tt2(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "tt2",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
